### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by hernangonzalez** [pajapro/fastlane-plugin-changelog#20]
Hello,

I am getting the following error on fastlane:

```
Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane_core/lib/fastlane_core/ui/interface.rb:150:in `user_error!': [!] Plugin 'changelog' was not properly loaded, make sure to follow the plugin docs for troubleshooting: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/PluginsTroubleshooting.md (FastlaneCore::Interface::FastlaneError)
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/runner.rb:161:in `rescue in trigger_action_by_name'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/runner.rb:155:in `trigger_action_by_name'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:29:in `block (2 levels) in parsing_binding'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/bin/fastlane:20:in `<top (required)>'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/bin/fastlane:22:in `load'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/bin/fastlane:22:in `<main>'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/hernangonzalez/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

I am using latest release. Any ideas what could be the root? I am not getting much info from the logs :/

Thank you,
H.

**Comment by hernangonzalez** [comment]
@pajapro do you have any comment on this? thank you

**Comment by pajapro** [comment]
Hey @hernangonzalez, sorry for late reply, but have you tried looking at [fastlane plugins troubleshooting](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/PluginsTroubleshooting.md)? 

Also, could you share the content of your `Pluginfile`?

**Comment by hernangonzalez** [comment]
hi @pajapro, i looked into the troubleshooting and I can only see that it fails to load. No useful message i could find.

Here is my pluginfile content:
```
# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

gem 'fastlane-plugin-changelog'
gem 'fastlane-plugin-appicon'
```

Thank you

**Comment by hernangonzalez** [comment]
I am now on `fastlane 2.26.1`, no idea how, though it looks like it is working. Thanks anyway.

**Comment by pajapro** [comment]
Great, glad to hear things work out for you @hernangonzalez
